In [3]:
%pylab inline
import numpy as np
a=[(2,3,4),(4,5,6),(6,7,8)]
b=np.array(a)
print np.shape(b)

Populating the interactive namespace from numpy and matplotlib
(3, 3)


In [4]:
a=np.array([1,2,3,4,5])
print np.shape(a)

(5,)


In [18]:
a=np.linspace(0,24,num=25,dtype=int)
print a.reshape(5,5)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
